### ISSUE TITLE
滑动后 裁剪组件样式覆盖在最上层？怎样解决？

### ISSUE THREAD

**Issue by w316431585** [SkinsTY/vue-img-clip#1]
![image](https://user-images.githubusercontent.com/46295716/50572364-48731f00-0dfa-11e9-8056-d0d94f32112f.png)

![image](https://user-images.githubusercontent.com/46295716/50572373-5de84900-0dfa-11e9-913d-92b677d30655.png)

**Comment by Tianyazz** [comment]
没太看懂，你这个是定位的问题吗？我是这么设置的，在组件外面包了一层。`<div class="avatar"><vue-clip></vue-clip></div>`，avatar设置宽高

**Comment by w316431585** [comment]
我在最外面也包裹了一层样式，我遇到的问题是 设置完头像后 下拉滑动后 编辑其他输入框的时候这个组件会挡住头部
![image](https://user-images.githubusercontent.com/46295716/50579818-6b95e100-0e83-11e9-918b-a411a4df2c28.png)

**Comment by w316431585** [comment]
是不是除了宽高 还要设置别的样式？
